# Generated by Django 4.0.8 on 2023-04-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbadges', '0005_remove_badgetype_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgetype',
            options={'ordering': ('validation_total',), 'verbose_name': 'Badge type', 'verbose_name_plural': 'Badge types'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ('-offered_on',), 'verbose_name': 'User badge', 'verbose_name_plural': 'User badges'},
        ),
        migrations.RemoveField(
            model_name='badgetype',
            name='finished_template',
        ),
        migrations.AddField(
            model_name='badgetype',
            name='finished_description',
            field=models.TextField(blank=True, default='', help_text='Text to be displayed for earned badges. ', verbose_name='Completed badge description'),
        ),
        migrations.AlterField(
            model_name='badgetype',
            name='unfinished_template',
            field=models.TextField(blank=True, default='', help_text='Template for the text to be displayed for badges which have not been earned yet. Use ${read_count} ${left_count} ${pluralize_stories_read} ${pluralize_stories_left} as placeholders for the total number of items already be read in category, the number of items left to be read, the translated plural form of the item type (story, article, ...)', verbose_name='In-progress badge description template'),
        ),
    ]
