# Generated by Django 4.0.8 on 2023-04-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbadges', '0006_alter_badgetype_options_alter_userbadge_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgetype',
            name='finished_description',
            field=models.TextField(blank=True, default='', help_text='Text to be displayed for earned badges', verbose_name='Completed badge description'),
        ),
    ]
