# Generated by Django 4.0.8 on 2023-03-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_userprofile_password_reset_retries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_uuid',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rapidpro_uuid',
            field=models.CharField(blank=True, db_index=True, default='', max_length=36, verbose_name='RapidPro Contact UUID'),
        ),
    ]
